org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890

org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true

kotlin.incremental=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true

kotlin.compose.compiler.metrics=true
kotlin.compose.compiler.reports=true